# .upper()
print("creat Pan card. Pleas enter your details")
name = input("What is your name: ").upper()
fname = input("What is your father's name: ").upper()
date_of_birth = input("What is your date of birth: ")

print(" _______________________________________________________ " )
print("| INCOME TAX DEPARTMENT                   GOVT.OF INDIA |" )
print("|  --------         Permanent Account Number Card       |" )
print("| |        |             MRPCT1230M          Qr code    |" )
print("| | PHOTO  |                              ''''''''''''' |" )
print("| |        |                              ''''''''''''' |" )
print("|  --------                               ''''''''''''' |" )
print("| Name                                    ''''''''''''' |" )
print(f"| {name:<30}          ''''''''''''' |" )
print("| Father's Name                                         |" )
print(f"| {fname:<30}                        |" )
print("| Date of Birth                                         |" )
print(f"| {date_of_birth:<30}                        |" )
print(" _______________________________________________________ " )
